console.log('util.js loaded');var UTIL=(function(){var utilObj={};utilObj.createDiv=function(_id,_class,_parent,_text){var _elem=document.createElement('div')
if(_id!=null&&_id!=undefined&&_id!=""){_elem.setAttribute("id",_id);}if(_class!=null&&_class!=undefined&&_class!=""){_elem.setAttribute("class",_class);}if(_parent!=null&&_parent!=undefined&&_parent!=""){var parentElem=(typeof _parent)==='string'?document.getElementById(_parent)||document.querySelector(_parent):_parent;parentElem.appendChild(_elem);}if(_text!=null&&_text!=undefined){_elem.innerHTML=_text;}return _elem;}
utilObj.createSpan=function(_id,_class,_parent,innerHTML){var _elem=document.createElement('span')
if(_id!=null&&_id!=undefined&&_id!=""){_elem.setAttribute("id",_id);}if(_class!=null&&_class!=undefined&&_class!=""){_elem.setAttribute("class",_class);}if(_parent!=null&&_parent!=undefined&&_parent!=""){if(typeof _parent=="string"){var parentElem=document.getElementById(_parent);parentElem.appendChild(_elem);}else{var parentElem=_parent;parentElem.appendChild(_elem);}}if(innerHTML!=null&&innerHTML!=undefined&&innerHTML!=""){_elem.innerHTML=innerHTML;}return _elem;}
utilObj.createOtherNode=function(_property,_id,_class,_parent,_text){var _elem=document.createElement(_property);if(_id!=null&&_id!=undefined){_elem.setAttribute("id",_id);}if(_class!=null&&_class!=undefined){_elem.setAttribute("class",_class);}if(_parent!=null&&_parent!=undefined&&_parent!=""){var parentElem=(typeof _parent)==='string'?document.getElementById(_parent)||document.querySelector(_parent):_parent;parentElem.appendChild(_elem);}if(_text!=null&&_text!=undefined){_elem.innerHTML=_text;}return _elem;}
utilObj.createVideoView=function(containerID,cc,isWatermark,watermarkIcon,watermarkUrl,watermarkRef){if(isWatermark==true){var hrefUrl=watermarkUrl;var _src=watermarkIcon;var wtmk=UTIL.createDiv("wtmk"+cc,"spl_wmk spl_show ania",containerID);var wtmkAnc=UTIL.createOtherNode("a","","spl_wmk spl_show ania",wtmk,"GOOGLE");var wtmkImg=UTIL.createOtherNode("img","","spl_wmk spl_show ania",wtmk);wtmkImg.onclick=function(){window.open(hrefUrl);}
wtmkAnc.setAttribute("href","#");wtmkAnc.setAttribute("target","_blank");wtmkImg.setAttribute("src",_src);}var videoViewDiv=UTIL.createDiv("videoview"+cc,"spl_FS",containerID);}
utilObj.createVideo=function(_id,_class,_parent,cc,_controls,_loop){var _elem=document.createElement('video')
if(_id!=null&&_id!=undefined){_elem.setAttribute("id",_id);}if(_class!=null&&_class!=undefined){_elem.setAttribute("class",_class);}_elem.setAttribute("class","spl_video");if(_controls==true){console.log('controls true');}else if(_controls==false){console.log('controls False do nothing');}else{console.log('controls undefined, so show');}if(_loop==true){_elem.setAttribute("loop","");}else if(_loop==false){console.log('loop False do nothing');}else{console.log('loop undefined, so show');}var isIOS=false;var parentElem=document.getElementById("videoview"+cc);parentElem.appendChild(_elem);return _elem;}
utilObj.createVideoAd=function(_id,_class,_parent,cc,_controls,_loop){var _elem=document.createElement('video')
if(_id!=null&&_id!=undefined){_elem.setAttribute("id",_id);}if(_class!=null&&_class!=undefined){_elem.setAttribute("class",_class);}if(_controls==true){console.log('controls true');}else if(_controls==false){console.log('controls False do nothing');}else{console.log('controls undefined, so show');}if(_loop==true){_elem.setAttribute("loop","");}else if(_loop==false){console.log('loop False do nothing');}else{console.log('loop undefined, so show');}if(_parent!=null&&_parent!=undefined&&_parent!=""){var parentElem=(typeof _parent)==='string'?document.getElementById(_parent)||document.querySelector(_parent):_parent;parentElem.appendChild(_elem);}return _elem;}
utilObj.getInfoContainerId=function(containerID){return"infoContainer"+containerID.charAt(containerID.length-1);}
utilObj.elem=function(elemID){return document.getElementById(elemID);}
utilObj.showInfo=function(containerID,msg){}
utilObj.CapitolCase=function(str){return str.toUpperCase();}
utilObj.getJson=function(url,cb){var xhttp=new XMLHttpRequest();xhttp.onreadystatechange=function(){if(this.readyState===4){if(this.status===200){try{var FeedObj=JSON.parse(this.responseText);cb(FeedObj);}catch(err){}}}};xhttp.open("GET",url,true);xhttp.send();}
utilObj.createVideoTag=function(playerContainerID,videoid,cc){var videoElem=UTIL.createVideo(videoid,"video",playerContainerID,cc);return videoElem;}
return utilObj;})();